openshift/devcenter

- README.md
> Updating README advice to avoid using web or rhc to deploy the site

- lib/en/python-flask.adoc
Reduce `http://http://` to `http://`.
> Fix URL to Flask website in python-flask.adoc

- lib/en/managing-environment-variables.adoc
- lib/en/php-getting-started.adoc
adding JAVA_OPTS_EXT to the environment variables section, and adding setting your document root section to php
> JAVA_OPTS_EXT and PHP document root selection

- lib/_layouts/home.html.haml
- lib/_partials/openshift-header.html.haml
> Updates Google Site Search refinement

- lib/_layouts/base.html.haml
- lib/_layouts/base_simple.html.haml
- lib/_layouts/home.html.haml
- lib/_layouts/jbossas.html.haml
- lib/_layouts/jbosseap.html.haml
- lib/_layouts/nodejs.html.haml
- lib/_layouts/perl.html.haml
- lib/_layouts/php.html.haml
- lib/_layouts/python.html.haml
- lib/_layouts/ruby.html.haml
- lib/_layouts/tomcat.html.haml
- lib/_layouts/zend.html.haml
- lib/_partials/analytics.html.haml
- lib/stylesheets/devcenter.css
> Adds Google Translate widget

- lib/en/managing-background-jobs.adoc
- lib/en/managing-deployments.adoc
- lib/en/managing-environment-variables.adoc
adding section on managing deployments, added cron example, fixed menu issue, and fixed compile errors in managing environment variables due to headings being out of order 
Should be able to close https://github.com/openshift/devcenter/issues/164 after this merge.
> some additions and fixes

- lib/en/managing-environment-variables.adoc
adding node.js environment variable example for https://github.com/openshift/devcenter/issues/243
> adding example for getting node.js environment variable for issue #243

- lib/en/node-js-example-meanstack.adoc
fixing issue https://github.com/openshift/devcenter/issues/242
> issue 242, fixing YOUR_APP_NAME to be openshift, which is the correct one

- lib/en/knowledge-base.adoc
> updating kb intro

- lib/en/databases-amazon-rds.adoc
- lib/en/databases-mongodb.adoc
- lib/en/databases-mysql.adoc
- lib/en/databases-overview.adoc
- lib/en/databases-postgresql.adoc
- lib/en/databases-sqlite.adoc
- lib/en/languages-overview.adoc
also edited the languages-overview page to remove the database section since databases will now have it's own overview page
> updating database section with new sqlite section and overview page

- lib/en/account-overview.adoc
> Adds account management section and faq

- lib/en/managing-environment-variables.adoc
- lib/en/perl-overview.adoc
- lib/en/php-framework-symfony.adoc
- lib/en/wildfly-overview.adoc
adding marker to perl page, changing wildfly version, and adding third way to view environment variables on env variables page, and fixing issue #269
> a few fixes

- lib/en/account-overview.adoc
- lib/en/managing-filesystem.adoc
- lib/en/troubleshooting-faq.adoc
> Adds troubleshooting FAQ and adds to account FAQ

- lib/_partials/openshift-header.html.haml
> Updates top navigation

- lib/en/php-environment-variables.adoc
- lib/en/php-framework-laravel.adoc
- lib/en/php-getting-started.adoc
> Updates Laravel, PHP getting started, adds PHP env vars

- lib/_partials/footer.html.haml
- lib/en/php-environment-variables.adoc
- lib/en/php-framework-laravel.adoc
- lib/stylesheets/devcenter.css
@spurtell @corey112358 Please merge
> Adds 'Powered by OpenShift' logo, updates PHP Laravel docs

- lib/en/marketplace-cine-io.adoc
- lib/en/marketplace-overview.adoc
> Updates Cine.io environment variable name

- lib/en/_fragments/java-jvm-memory.adoc
- lib/en/jbossas-jvm-memory.adoc
- lib/en/jbosseap-jvm-memory.adoc
- lib/en/tomcat-jvm-memory.adoc
- lib/en/wildfly-jvm-memory.adoc
adding sections on the default JVM memory available, and how to modify it
> JVM Memory Sections

- lib/en/marketplace-statica.adoc
- lib/en/php-framework-laravel.adoc
> Updates Laravel, fixes Statica

- lib/en/java-overview.adoc
- lib/en/jbosseap-overview.adoc
- lib/en/xpaas.adoc
> Updates JBoss EAP content for 6.4 release

- lib/en/jbosseap-overview.adoc
- lib/en/managing-environment-variables.adoc
- lib/en/managing-scaling.adoc
- lib/en/xpaas.adoc
adding information about the scaling environment variable and fixing  a couple of bad ascii issues
> scaling env variables & bad ascii fixes

- lib/en/managing-client-tools.adoc
https://bugzilla.redhat.com/show_bug.cgi?id=1222021
> Updates rhc documentation

- lib/en/node-js-environment-variables.adoc
To address https://github.com/openshift/devcenter/issues/309
> Fixes variable name per issue 309

- lib/en/marketplace-cine-io.adoc
- lib/en/marketplace-cleardb-mysql-database.adoc
- lib/en/marketplace-cloudamqp.adoc
- lib/en/marketplace-elephantsql.adoc
- lib/en/marketplace-ironmq.adoc
- lib/en/marketplace-ironworker.adoc
- lib/en/marketplace-memcached-cloud.adoc
- lib/en/marketplace-memcachier.adoc
- lib/en/marketplace-mongolab.adoc
- lib/en/marketplace-new-relic.adoc
- lib/en/marketplace-overview.adoc
- lib/en/marketplace-redis-cloud.adoc
- lib/en/marketplace-searchly.adoc
- lib/en/marketplace-sendgrid.adoc
- lib/en/marketplace-statica.adoc
> Updates Marketplace environment variable documentation

- lib/_partials/openshift-header.html.erb
@spurtell Please merge and publish
> Updates navigation menu

- lib/en/_fragments/getting-started-setup.adoc
To help with https://github.com/openshift/devcenter/issues/323
> Updates rhc setup fragment

- lib/en/managing-common-rhc-commands.adoc
Resolves https://github.com/openshift/devcenter/issues/325
> Updates common RHC commands to current versions

- lib/.htaccess
Fixing an htaccess redirect for contact form, and adding one for /hc/en-us
> updating htaccess file

- lib/_partials/openshift-header.html.erb
> Updates link to YouTube

- lib/_layouts/base.html.haml
- lib/_layouts/base_simple.html.haml
- lib/_layouts/home.html.haml
- lib/_layouts/jbossas.html.haml
- lib/_layouts/jbosseap.html.haml
- lib/_layouts/nodejs.html.haml
- lib/_layouts/perl.html.haml
- lib/_layouts/php.html.haml
- lib/_layouts/python.html.haml
- lib/_layouts/ruby.html.haml
- lib/_layouts/tomcat.html.haml
- lib/_layouts/wildfly.html.haml
- lib/_layouts/zend.html.haml
- lib/_partials/analytics.html.erb
- lib/_partials/analytics.html.haml
@spurtell Please merge/publish
> Updates tracking to Google Tag Manager

- lib/en/jbosseap-getting-started.adoc
- lib/en/python-getting-started.adoc
- lib/en/tomcat-getting-started.adoc
- lib/en/xpaas-fuse.adoc
fixes for https://github.com/openshift/devcenter/issues/352 and https://github.com/openshift/devcenter/issues/342
> fixing typos and links

- lib/_layouts/home.html.haml
@coreydaley Please merge and deploy
> Fixes Google Search autocomplete on home page

- lib/stylesheets/devcenter.css
* Fixes #359
Signed-off-by: Joao Goncalves <jgoncalv@redhat.com>
> ISSUE-359: Fixing table overflows

- lib/stylesheets/devcenter.css
* Adds minor changes to h1, h2 and h3 styles (closes #240)
> style: Improve header differentiation

- lib/_partials/footer.html.haml
- lib/_partials/openshift-header.html.erb
@suspect-zero Please merge and push to prod
> Updates menu navigation and footer

- .gitignore
- README.md
* Updates the deployment guides (#366)
* Adds _site as a single file to .gitignore to prevent unwanted git add
> README: Deployment update

- lib/en/_fragments/overview-extend-create-quickstart.adoc
> docs: fix broken new quickstart link

- lib/_partials/openshift-header.html.erb
@corey112358 Please merge and publish
> Fixes typo in navigation

- lib/_partials/openshift-header.html.erb
@jsvgoncalves @corey112358 Please merge and publish
> Adds OpenShift Dedicated general availability

- lib/_layouts/base.html.haml
- lib/_layouts/base_simple.html.haml
- lib/_layouts/jbossas.html.haml
- lib/_layouts/jbosseap.html.haml
- lib/_layouts/nodejs.html.haml
- lib/_layouts/perl.html.haml
- lib/_layouts/php.html.haml
- lib/_layouts/python.html.haml
- lib/_layouts/ruby.html.haml
- lib/_layouts/tomcat.html.haml
- lib/_layouts/wildfly.html.haml
- lib/_layouts/zend.html.haml
- lib/en/report.html.erb
* Adds a new page with additional information about report a
documentation content issue (Closes #377)
> Add content issue report page

- lib/en/managing-domains-ssl.adoc
* Adds a small guideline for custom certificates w/ link to RH docs
> docs: Add custom certificates guidelines

- lib/en/managing-markers.adoc
* New article "Markers"
* added links to documented markers
* basic info about creating a marker
* closes issue #237 
can be previewed [here](https://devcenter-jfiala.rhcloud.com/en/managing-markers.html)
> Marker links

- lib/en/xpaas.adoc
@corey112358 @jsvgoncalves Please merge and deploy
> Removes JBoss Fuse reference on xPaaS main page

- lib/_layouts/base.html.haml
- lib/_layouts/base_simple.html.haml
- lib/_layouts/home.html.haml
- lib/_layouts/jbossas.html.haml
- lib/_layouts/jbosseap.html.haml
- lib/_layouts/nodejs.html.haml
- lib/_layouts/perl.html.haml
- lib/_layouts/php.html.haml
- lib/_layouts/python.html.haml
- lib/_layouts/ruby.html.haml
- lib/_layouts/tomcat.html.haml
- lib/_layouts/wildfly.html.haml
- lib/_layouts/zend.html.haml
@corey112358 @jsvgoncalves Please merge and deploy
> Adds canonical tag for SEO

- lib/en/managing-remote-connection.adoc
* link SSH keys guide to the [OSO User Guide, 3.2.2](https://access.redhat.com/documentation/en-US/OpenShift_Online/2.0/html/User_Guide/Generating_Keys_Manually4.html)
* fixes #415
> Fix SSH keys manual doc link

- lib/en/managing-environment-variables.adoc
Minor enhancements of the [Using Environment Variables](https://developers.openshift.com/en/managing-environment-variables.html) article
Closes #428 
Can be previewed [here](https://devcenter-jfiala.rhcloud.com/en/managing-environment-variables.html)
> Issue#428 - env vars update

- lib/stylesheets/devcenter.css
* fix search field bottom padding (home page + search page)
* fix vertical alignment of the search page btn
closes #430
> Fix search field padding

- README.md
Updating the readme with new instructions based on using Middleman and Travis CI
> updating README file for middleman

- source/faq/troubleshooting.adoc
- source/managing-your-applications/common-rhc-commands.adoc
- source/servers/tomcat/getting-started.adoc
* tech FAQ: traffic estimates answer update
* tech FAQ -> list: missing CRLF
* tomcat -> getting-started: fix markers table
* common-rhc-commands: H2 IDs added
* closes #439
> faq: troubleshooting - traffic estimates

- data/tree.yml
- source/core-addons/index.adoc
- source/core-addons/phpmyadmin.adoc
- source/core-addons/rockmongo.adoc
* mention RockMongo in Core Addons, closes #463
Can be previewed here:
https://stage-jfiala.rhcloud.com/core-addons/
https://stage-jfiala.rhcloud.com/core-addons/rockmongo.html
> docs: add RockMongo

- source/languages/nodejs/markers.adoc
* minor: remove duplicate title from nodejs - markers
> languages: remove duplicate title

- source/languages/python/flask.adoc
* flask-tutorial: reword the flask quickstart reference; closes #459
> languages: python - flask quickstart

- source/managing-your-applications/regions-and-zones.adoc
* Use the same link that's on the openshift.com contact page
* closes #477
NOTE: This avoids the https://ideas.openshift.com cert. CN issue.
> managing: regions - update uservoice link

- source/languages/python/getting-started.adoc
Fixing issues detailed via this bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1342721
> fixing a couple of 404 links

- source/core-addons/phpmyadmin.adoc
- source/core-addons/rockmongo.adoc
- source/databases/index.adoc
- source/languages/nodejs/dependency-management.adoc
- source/languages/nodejs/environment-variables.adoc
- source/languages/nodejs/example-meanstack.adoc
- source/languages/nodejs/getting-started.adoc
- source/languages/nodejs/index.adoc
- source/languages/nodejs/project-structure.adoc
- source/servers/jbossas/getting-started.adoc
- source/servers/jbosseap/getting-started.adoc
- source/servers/vertx.adoc
* removed a couple of duplicate h1's
* minor formatting amends along the way
> remove duplicate headers

- source/managing-your-applications/idling.adoc
* updated app idling information
> managing: update idling info

- source/faq/account.adoc
* adds a few more details into the "account downgrade" question
> faq: account downgrade

- source/managing-your-applications/regions-and-zones.adoc
- source/managing-your-applications/resource-management.adoc
- source/managing-your-applications/scaling.adoc
- source/overview/platform-features.adoc
* removes obsolete Dedicated Node Service information
* replaced with OpenShift Dedicated, where suitable
> various: update Dedicated info

- source/faq/account.adoc
* removes info involving new account sign up
* removes references to grants program
* updates email address change instructions
> faq: update account info

- source/overview/books.adoc
* fixed "OpenShift for Developers" book cover thumbnail link
> overview: book link fix

- source/layouts/_navbar.erb
- source/layouts/layout.erb
- source/search.html.erb
- source/stylesheets/devcenter.css
* replaces the site search with Fess
* search scope only within the devcenter (v2)
> search: replace site search with Fess

- source/.htaccess
* redirects the contact form to the new form at help.openshift.com
> htaccess: redirect contact form
