- lib/en/python-flask.adoc
We must check for __main__ in global scope, not in a function.
> Fix indentation in flask doc

- lib/en/node-js-project-structure.adoc
node-js-project-structure.adoc: Fix typo in variable name
> [small typo] Fix typo in variable name

- lib/en/php-markers.adoc
- Adds consistent use of a dot `.` at the end of each sentence
- Uses full word for `dependencies` instead of abbreviation
- Makes `composer install` look like an actual command
> Minor improvement to the PHP marker file.

- lib/en/managing-domains-ssl.adoc
https://bugzilla.redhat.com/show_bug.cgi?id=1256427
When creating a CSR on a gear, openssl (by default) attempts to create a 'random state' file at `$HOME/.rnd`. Users do not have write permissions on the root of their home directory, resulting in an error reported by openssl. Ensure the 'random state' file, as well as the key file, are created in the user-writable directory $OPENSHIFT_DATA_DIR.
> Bug 1256427 - Random state file and Key file should be created in $OPENSHIT_DATA_DIR

- lib/en/getting-started-debian-ubuntu.adoc
`rubygems` are now installed installed within `ruby-full`, `rubygems-integration` package does not seem to be required for OpenShift client tools.
Tested on brand new virtual machines Ubuntu 14.04 LTS and 15.10 (i.e. default apt sources for trusty and wily), not tested on Debian
Removed step 2 from getting started for the Debian/Ubuntu. 
Can be previewed here:
https://devcenter-jfiala.rhcloud.com/en/getting-started-debian-ubuntu.html#client-tools-gem
@suspect-zero, please review
> Issue#370: 

- lib/en/tomcat-markers.adoc
This marker was removed shortly after its addition due to java8 not being supported with jbossews-2.0. The marker was removed with commit:
https://github.com/openshift/origin-server/commit/833c5ea1778cb9279ef53cdac99f3e879adee1d4
> Remove the documentation for the java8 tomcat marker

- lib/en/managing-filesystem.adoc
No isse created for this, small change only:
* Reduced the additional storage set to 5 (6 is not available)
* a short info on modification via the web interface was added
Can be previewed at:
https://devcenter-jfiala.rhcloud.com/en/managing-filesystem.html#_resolving_disk_space_issues
> Silver cartridge storage set 6->5

- lib/en/getting-started-windows.adoc
Multiple customers on windows are reporting issues with installing the latest version of Ruby. As it turns out, the latest v2.x versions do not work. Only the latest v1.9 versions do. It is not clear on the version outside of the "Tip" which should be placed first. Hopefully, this correction removes the confusion.
> Updated getting-started-overview.html b/c of Ruby version issue

- lib/en/managing-domains-ssl.adoc
Bug 1268317, Bug 1281901, Bug 1269637
Bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1268317
Bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1281901
Bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1269637
Removing SSL Certificate Chain Field from web console,
see https://github.com/openshift/origin-server/pull/6342
Document that the user must concatenate SSL cert files into a single file to upload,
or upload the already-concatenated file included in the SSL certificate from
the SSL certificate provider.
> Document changes needed for removal of Cert Chain Field from web console

- lib/en/help.html.erb
- lib/en/report.html.erb
* Adds a reference to the mailing list both on the help and
report page (closes #408)
> Add mailing list link

- lib/en/getting-started-windows.adoc
bz1303820
bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1303820
When installing git for Windows, in order to run 'rhc setup' from
Git Bash, terminal emulator must be configured with "Windows' default console window"
rather than "MinTTy".  Otherwise, 'rhc setup' hangs when user enters
OpenShift Online password.  'rhc setup' works fine with MinTTY from Ruby Cmd Prompt, Powershell.
> Recommend Windows' default console window with git for Win install

- lib/en/managing-markers.adoc
- lib/en/node-js-markers.adoc
- lib/en/node-js-project-structure.adoc
* add a dedicated Markers page for Node.js
* remove duplicate content from "Project Structure"
* add links to markers and action hooks on top (standard)
* rename "Project Structure" to "Repository Layout" (standard)
* transform the mention of `deplist.txt` into a note
* closes #432
Notes:
This change makes the Node.js section more consistent with other
Language sections. It is still using the "node-js-project-structure"
file (thus no redirect needed).
The changes can be previewed here:
https://devcenter-jfiala.rhcloud.com/en/nodejs-markers.html
https://devcenter-jfiala.rhcloud.com/en/node-js-project-structure.html
> Add Node.js Markers page

- lib/en/addons-phpmyadmin.adoc
- lib/en/databases-mysql.adoc
- lib/en/managing-domains-ssl.adoc
- lib/en/managing-port-binding-routing.adoc
* add a note about custom SSL certficates not available with wss to:
- Port binding and routing
- Domains and SSL
* link port forwarding from the phpMyAdmin page (scalable note)
* link phpMyAdmin addon from the MySQL page
* closes #437
The mentioned changes can be previewed here:
https://devcenter-jfiala.rhcloud.com/en/managing-port-binding-routing.html
https://devcenter-jfiala.rhcloud.com/en/managing-domains-ssl.html#using-a-custom-ssl-certificate
https://devcenter-jfiala.rhcloud.com/en/addons-phpmyadmin.html
https://devcenter-jfiala.rhcloud.com/en/databases-mysql.html#phpmyadmin
> wss SSL cert, scalable MySQL/phpMyAdmin

- source/getting-started/windows.adoc
* getting-started: add recommended RubyInstaller version for Windows
- that is (1.9.3 and 2.0.0)
* closes #445
NOTE: Based on the community feedback, these versions are known to
work well with rhc tools, unlike some newer Ruby versions on Windows.
This change can be previewed [here](https://devcenter-jfiala.rhcloud.com/getting-started/windows.html#client-tools).
> Add recommended RubyInstaller version

- source/managing-your-applications/domains-ssl.adoc
* Adds a link to RFC1123 which documents valid hostname/subdomain
syntax.
This change follows Bugzilla #1329915 [1], PR #6384 on
openshift/origin-server/#6384 [2] and issue #451 on
openshift/devcenter/#451 [3]. (closes #451)
[1] - https://bugzilla.redhat.com/show_bug.cgi?id=1329915
[2] - https://github.com/openshift/origin-server/pull/6384
[3] - https://github.com/openshift/devcenter/issues/451
> docs: add link to rfc1123

- source/getting-started/osx.adoc
* Based on #448, El Capitain users might have to run gem install with a
option for the path. (closes #448)
> docs: add rhc install fix for Mac OS

- source/getting-started/debian-ubuntu.adoc
because "sudo apt-get install rhc" actually leads to a completely broken rhc; see https://bugzilla.redhat.com/show_bug.cgi?id=1291628
> Remove broken Installing the Client Tools via dpkg

- source/managing-your-applications/linux-commands.adoc
- source/managing-your-applications/remote-connection.adoc
This ads an explicit root privilege notice and a backup tip to ssh and common linux commands articles. Can be previewed here:
https://devcenter-jfiala.rhcloud.com/managing-your-applications/linux-commands.html
https://devcenter-jfiala.rhcloud.com/managing-your-applications/remote-connection.html#connecting-to-your-application
> docs: add a root privilege note

- source/languages/nodejs/getting-started.adoc
* Fixes the markdown syntax for the link which was invalid and also 404,
closes #467.
> docs: fix nodejs getting started 404 link

- source/getting-started/windows.adoc
One of the recommended versions (2.0.0) is available on the download page, but the archive page does not have the most recent security patches available. I changed the link to point to the download page instead of the archive page. Archives can still be reached from the download page with a single click if the user prefers version 1.9.3.
> Point to RubyInstaller downloads instead of archives

- source/faq/troubleshooting.adoc
* adds a note for the node.js 0.10 quick start https redirect in FAQ
* closes #485
> faq: node.js https redirect

- source/layouts/_navbar.erb
Fixed typo in the hostname mentioned in the navbar
> Fixed typo in navbar for old doc version

- source/.htaccess
* redirects help.openshift.com to the help page (was index page)
> htaccess: redirect help.openshift.com

- source/faq/account.adoc
- source/index.adoc
- source/languages/nodejs/example-meanstack.adoc
- source/managing-your-applications/domains-ssl.adoc
- source/managing-your-applications/idling.adoc
- source/managing-your-applications/resource-management.adoc
- source/overview/platform-features.adoc
As the "legacy" pricing page is not available, the obsolete references (now pointing to v3 pricing page with only the *Starter* plan being there) were removed or replaced with a direct link to the console for users to upgrade their plan.
----
* replaces the customer service contact email with a whole list of
available customer service worldwide contacts
* removes obsolete pricing links or replaces them with account upgrade
link, where suitable
> faq: update Customer Service contact

- source/layouts/_navbar.erb
- source/layouts/base.erb
- source/layouts/home.erb
- source/layouts/layout.erb
- source/stylesheets/devcenter.css
* permanently displays the v2 top info banner
* updates the text slighly
* still leads to docs.openshift.com, the whole div is clickable
> layouts: permanent v2 banner
